version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: product-trial-db
    environment:
      POSTGRES_DB: product_trial
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - product-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-trial-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_trial
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - product-network

volumes:
  postgres_data:

networks:
  product-network:
    driver: bridge